### ISSUE TITLE
Get the team_assigned_id field in conversation model

### ISSUE THREAD

**Issue by marie-aircall** [fivetran/dbt_intercom_source#10]
Hi team!

I don't find the team_assigned_id linked to each intercom conversation. Do you think it could be possible to add it? That would help me a lot as assignees can be part of several teams I can't just join the assignee to the team_admin table.

Thanks a lot for your help!

Best,
Marie

**Comment by fivetran-joemarkiewicz** [comment]
Hi @marie-aircall thanks for opening this Issue for the request to add the assignee team reference to a conversation. This should be a relatively easy lift to join the team into the `intercom__conversation_enhanced` model within the [intercom transformation](https://github.com/fivetran/dbt_intercom) dbt package. 

I will add this task to our next SPRINT to add the functionality you are describing. In addition, we are always happy to support community contributions if you wanted to open a PR that incorporates this change! 🎉 Otherwise, I will continue communication here when I am able to get a working branch going for you!

Thanks again 😄

**Comment by fivetran-joemarkiewicz** [comment]
Hi @marie-aircall I wanted to give you an update that we are still planning to work on this feature request. However, we are prioritizing the upgrading of the package to dbt 20 compatibility. Once we upgrade the package we will focus on adding this functionality to the following release.

**Comment by fivetran-jamie** [comment]
@marie-aircall taking a look at this now -- so by `team_assigned_id` are you referring to the `team_id(s)` associated with the `conversation.assignee_id`? if so, would you want to see an aggregated list of `team_ids` (and/or `team_names`) that the user assigned to a conversation belongs to? just wanna clarify since there's also the conversation_part level which has `assigned_to_id` and `author_id` as well ([details on these IDs in ERD](https://docs.google.com/presentation/d/1K3HTGqNQ-neUNeTtjJq42RHBV68_4FuXFp8X81zJ5Xo/edit#slide=id.p))

**Comment by fivetran-jamie** [comment]
thinking through the details of this more, it might be good to talk this out over a meeting if you're down! 

https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2021-08

**Comment by fivetran-joemarkiewicz** [comment]
Closing this Issue as the solution was merged into the latest release.
